#!/bin/bash

LIBS=$(pkg-config --libs lua)

PROGS="alter-state array callback override pass-variable return-value simple-call"

for i in $PROGS; do
	echo "---------------------------------------"
	echo "${i^^}"
	echo
	gcc -Wall $LIBS -o $i $i.c || break
	./$i
	echo
done

