#!/bin/bash

LIBS=$(pkg-config --libs lua)

gcc -Wall $LIBS -o lua1 lua1.c
gcc -Wall $LIBS -o lua2 lua2.c
gcc -Wall $LIBS -o lua3 lua3.c
gcc -Wall $LIBS -o lua4 lua4.c

echo
./lua1
echo
./lua2
echo
./lua3
echo
./lua4
echo

