#!/bin/bash

LIBS=$(pkg-config --libs lua)

for i in {1..5}; do
	gcc -Wall $LIBS -o lua$i lua$i.c || break
	echo
	./lua$i
done

echo
gcc -Wall $LIBS -o array array.c
./array

echo
gcc -Wall $LIBS -o override override.c
./override
echo

